server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.72.128:3306/tensquare_qa?characterEncoding=UTF-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
