server:
  port: 12000
spring:
  application:
    name: tensquare_config
  rabbitmq:
    host: 192.168.72.128
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/inta/tensquare_dev.git
management:
  endpoints:  # 暴露bus 接口 ，否则 更新 refresh 没用的
    web:
      exposure:    # expose: "*" 已过期
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true